spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  context-path: /jpa