spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
